DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.00003
  WEIGHT_DECAY: 0.1
  MAX_EPOCH: 500
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 50
  WARMUP_TYPE: "linear"
  WARMUP_MIN_LR: 1e-7

TRAIN:
  PRINT_FREQ: 100

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  FTCLIP:
    METHOD: "ft"