DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.5
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  MAX_EPOCH: 500
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 50
  WARMUP_TYPE: "linear"
  WARMUP_MIN_LR: 0.001

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  BLACKVIP:
    METHOD: "coordinator"
    PT_BACKBONE: 'vit-mae-base'
    SRC_DIM: 1568
    E_OUT_DIM: 0
    SPSA_PARAMS: [1.0,0.01,0.01,0.4,0.1]
    OPT_TYPE: "spsa-gc"
    MOMS: 0.9
    SP_AVG: 5
    P_EPS: 1.0